server:
  port: 8083

spring:
  application:
    name: aggregator-service
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.codeus.hyperloglog: INFO

app:
  scheduling:
    enabled: true
